# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
