# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wormuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
