# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171006_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(db_index=True)),
                ('coord_y', models.IntegerField(db_index=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(db_index=True)),
                ('coord_y', models.IntegerField(db_index=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(db_index=True)),
                ('coord_y', models.IntegerField(db_index=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_num', models.IntegerField(db_index=True)),
                ('level_num', models.IntegerField(db_index=True)),
                ('scenario_size_width', models.IntegerField()),
                ('scenario_size_height', models.IntegerField()),
                ('speed', models.FloatField()),
                ('worm_type', models.IntegerField()),
                ('bacteria', models.ManyToManyField(to='api.Bacterium')),
                ('decors', models.ManyToManyField(to='api.Decor')),
                ('obstacles', models.ManyToManyField(to='api.Obstacle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WormUser')),
            ],
        ),
    ]
