# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bacterium_decor_obstacle_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('turn_right', 'Turn right'), ('turn_left', 'Turn left'), ('collision', 'Player crashed against an obstacle'), ('element_viewed', 'Player discovered resource'), ('element_caught', 'Player picked up resource'), ('start', 'Player started game'), ('end', 'Player ended game')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_remaining', models.FloatField()),
                ('total_points', models.IntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scenario')),
            ],
        ),
        migrations.AlterField(
            model_name='bacterium',
            name='coord_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bacterium',
            name='coord_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='decor',
            name='coord_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='decor',
            name='coord_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='coord_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='coord_y',
            field=models.IntegerField(),
        ),
    ]
