# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171006_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='wormuser',
            name='wormname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
