# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wormuser_wormname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='wormname',
            field=models.CharField(max_length=150),
        ),
    ]
