# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171009_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='birth_date',
            field=models.CharField(max_length=8),
        ),
    ]
