# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171009_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('bacterium', 'Small microscopic life form'), ('decor', 'So pretty'), ('obstacle', 'Ouch. Not this way')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='bacteria',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='decors',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='obstacles',
        ),
        migrations.DeleteModel(
            name='Bacterium',
        ),
        migrations.DeleteModel(
            name='Decor',
        ),
        migrations.DeleteModel(
            name='Obstacle',
        ),
        migrations.AddField(
            model_name='sceneentity',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scenario'),
        ),
    ]
