# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_wormuser_wormname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
