# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171010_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='level_num',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='world_num',
        ),
        migrations.AddField(
            model_name='scenario',
            name='level_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='world_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='worm_type',
            field=models.CharField(max_length=50),
        ),
    ]
