# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20171010_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='level_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='world_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
