# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171010_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='total_points',
            new_name='action_timestamp',
        ),
        migrations.RemoveField(
            model_name='action',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='action',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='token_partida',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
