# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171017_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
    ]
