# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171018_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='token_partida',
            field=models.CharField(default='', max_length=150),
        ),
    ]
