# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_action_token_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.Scenario'),
        ),
    ]
