# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20171019_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='scenario',
        ),
    ]
