# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20171023_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormuser',
            name='birth_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wormuser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
